### ISSUE TITLE
Any plan to support iOSSnapshotTestCase?

### ISSUE THREAD

**Issue by ignazioc** [TitouanVanBelle/XCTestHTMLReport#100]
Hi, We are using this tool and we really like it. 
We also use iOSSnapshotTestCase and it would be great to see the failed snapshot also there.

Any plan to support?

**Comment by TitouanVanBelle** [comment]
Hi @ignazioc 

No there is no plan to support this tools. But you can probably easily add the failed snapshot by adding an activity to you test report and adding an attachment to that activity
