### ISSUE TITLE
After running 2 suites of tests on the same device, viewing the results in the same report is not supported

### ISSUE THREAD

**Issue by BobbyRohweder** [TitouanVanBelle/XCTestHTMLReport#102]
Since tests were run on the same device in sequence, the identifier is the same in devices list on the left in the viewer

when trying to click on any test results, it does not update the viewer since the identifier is the same;
both have on `onclick="selectDevice('identifier', this);"` with identical values

**Comment by TitouanVanBelle** [comment]
Hi @BobbyRohweder 

Thanks for the report. I fixed it on branch 102_running_twice_same_device. Can you check it out to see if that works for you. I'm not sure exactly how you run your tests and create the report so I'm not sure the solution will work.

Let me know
