### ISSUE TITLE
Invalid xml with unescaped tag

### ISSUE THREAD

**Issue by tbrand** [TitouanVanBelle/XCTestHTMLReport#103]
I faced an error of invalid xml which cannot be parsed by unescaped tag `<>` like this.
```xml
<testcase classname='MyTests - iPhone 6s - 12.0' name='sample_test()' time='1.26'>
  <failure>
    Assertion Failure: MyTests.swift:88: XCTAssertNil failed: "<MyViewController: 0x7fd99fe00000>" -
  </failure>
</testcase>
```

The failed test looks like
```swift
XCTAssertNil(self.myController.presentedViewController)
```

I think [this line](https://github.com/TitouanVanBelle/XCTestHTMLReport/blob/develop/XCTestHTMLReport/XCTestHTMLReport/Classes/Models/JUnitReport.swift#L101) should be escaped?

Thanks

**Comment by TitouanVanBelle** [comment]
Hi @tbrand 

Thanks for the report. Could you upload a bundleResults I can work with to reproduce the issue and also the command you execute to generate the report
Thanks

**Comment by tbrand** [comment]
Sorry it's production app thus I cannot post logs and commands. 😢

**Comment by TitouanVanBelle** [comment]
What about reproducing the issue in a new project?

**Comment by taisukeh** [comment]
It can be easily reproduced by this assertion.
```
XCTAssertEqual("foo", "<a> foo")
```
