### ISSUE TITLE
Unknown failure produces invalid xml for junit report

### ISSUE THREAD

**Issue by nfrydenholm** [TitouanVanBelle/XCTestHTMLReport#112]
If the app e.g. crashes during a test, it produces some xml that causes junit reporting on e.g. Jenkins to fail.

An example from the xml output
```
 <failure>
        Assertion Failure: <unknown>:0: Unexpected test interruption without any failures reported
        Assertion Failure: <unknown>:0: [Apptarget] crashed in CLSTerminateHandler()
      </failure>
```
That leads to errors parsing the report.junit file, as the `<unknown>` is not being terminated.

Same result using version 1.6.1 and HEAD.

I'm using Xcode 10, and will try to make a demo project that reproduces the error, so I can share the result bundle.

**Comment by TitouanVanBelle** [comment]
Yes it will be available in 1.7.0 which is going to be released sometime this month.

**Comment by nfrydenholm** [comment]
@TitouanVanBelle any update on when 1.7.0 will be released? 😃

**Comment by nfrydenholm** [comment]
@TitouanVanBelle will there be a release coming out before Christmas/New Year? 🤞 🎅 🎆

**Comment by nfrydenholm** [comment]
@TitouanVanBelle any news on when we can expect the next release?
