### ISSUE TITLE
illegal hardware instruction  xchtmlreport -r TestResults

### ISSUE THREAD

**Issue by repl-ullas-ml** [TitouanVanBelle/XCTestHTMLReport#113]
Get this error on macOS 10.14

I have been yearning for a tool like this for a while and this tool served me well. Very recently i bumped my mac os to 10.14, and the tool stopped working.

**Comment by repl-ullas-ml** [comment]
@TitouanVanBelle Any idea what might be causing this? When it comes to viewing the test results from the CI your plugin is a saviour for us. With this issue, we have been facing some inconvenience. Help us. Thanks for such an awesome plugin

**Comment by repl-ullas-ml** [comment]
<img width="594" alt="screen shot 2019-01-03 at 4 34 52 pm" src="https://user-images.githubusercontent.com/11545334/50667284-c1e34c80-0f75-11e9-91a1-30cda3833922.png">

**Comment by LeepengX** [comment]
my macOS is 10.14.1 now. Evrything is fine....
