### ISSUE TITLE
May it have affected the test results？

### ISSUE THREAD

**Issue by LeepengX** [TitouanVanBelle/XCTestHTMLReport#120]

**Comment by LeepengX** [comment]
**Assertion Failure:0:failed:Timed out after waiting 1.0s for KeyEventConpleted after sending event for 'q'.(0s).**
I never met this until I used XCTestHTMLResult in my XCUITest command.
Have you guys met this ?

**Comment by LeepengX** [comment]
When type text to a secureTextField, I met this problem.
Sorry.
Will this technology affect the testing process, please？

**Comment by TitouanVanBelle** [comment]
No this technology does not affect the testing process. It only creates an HTML reports based on the already existing test results.
