### ISSUE TITLE
Invalid xml Junit file

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [TitouanVanBelle/XCTestHTMLReport#131]
Some times the tool produces incorrect XML file like `<unknown>` as a result the junit is not valid, could we escape `<>` arrows for the failure message  

```
<testcase classname='ChannelPickerPhoneUITests - iPhoneÃ¢??s iPhone - 10.3.3' name='testChannelPicker()' time='131.37'>
<failure>
 Assertion Failure: <unknown>:0: Application com.example.test is not running
 </  failure>
</testcase>

```

Error using XML validator
```
The element type "unknown" must be terminated by the matching end-tag "</unknown>".
```

**Comment by cianiandreadev** [comment]
+1

**Comment by cianiandreadev** [comment]
In my case I figured out was a problem in one of my unit tests that was failing with an unknown reason.
This lead to a unparsable result for XCTestHTMLReport. Maybe this can be useful for others.

**Comment by TitouanVanBelle** [comment]
@Ashraf-Ali-aa Can you provide a result bundle that reproduces the error. And also an expected result.

**Comment by AhmedOsamaBarghash** [comment]
Where is the Junit XML file located!

**Comment by nacho4d** [comment]
This has been previously fixed in this commit: https://github.com/TitouanVanBelle/XCTestHTMLReport/commit/92ab70381804a355541ce5787bca02f65596a645

Also in this MR https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/196 tests have been added so this problem should not happen for XMLs anymore.
