### ISSUE TITLE
Attachments from '1_Test/Attachments' are pointed by html file

### ISSUE THREAD

**Issue by prakashsarav7** [TitouanVanBelle/XCTestHTMLReport#134]
Attachments are copied from directory '1_Test/Attachments' to directory 'Attachments' while creating html report. But still the files from directory '1_Test/Attachments' are pointed in the html report

**Comment by TitouanVanBelle** [comment]
Attachments are not copied over to the Attachments folder by xchtmlreport. The result bundle is provided by Xcode like that.
