### ISSUE TITLE
Xcode 11 support

### ISSUE THREAD

**Issue by FabienLydoire** [TitouanVanBelle/XCTestHTMLReport#137]
Hello !

Xcode 11 changes the format of the Test bundle files.
I know that Xcode 11 is able to re-open a Test bundle and display the content.
Nevertheless having an HTML version of the Test bundle is very handy.

Is there a plan to support the new format with XCTestHTMLReport ?

**Comment by TitouanVanBelle** [comment]
Yes there is a plan to support. I just need to wait for Xcode 11 to finish downloading :)

**Comment by IlyaMakarevich** [comment]
Hi! Did you finish downloading?

**Comment by forceunwrap** [comment]
Any update on this?

**Comment by FabienLydoire** [comment]
Xcode 11 GM has been released 10/9/2019.
@TitouanVanBelle Can you tell if you plan to update XCTestHTMLReport now that we can re-open an existing TestBundle in Xcode ?
Will this project be dropped ?

**Comment by jreyesv** [comment]
Is the project going to be dropped? There are still use cases for having HTML Test reports. Not everyone has Xcode but almost everyone has a browser, to check results of CI/CD is very convenient. 

Any updates on this?

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : When running on XCode 11 with an iOS 13 simulator this is the error we get due to which the report fails to generate:
```
xchtmlreport -r TestResults1 -r TestResults2 -v -j
XCTestHTMLReport 1.7.0

Parsing Test Summaries
▸ Searching for action_TestSummaries.plist in TestResults1
Error: Failed to find action_TestSummaries.plist in TestResults1
```
If you would need anything else from our end, then kindly let us know. It would be nice to get this fixed.

**Comment by chrisballinger** [comment]
Perhaps this could be resolved by integrating with this other tool that parses the new Xcode 11 xcresult format: https://github.com/ChargePoint/xcparse

**Comment by kenji21** [comment]
another solution could be to use https://github.com/davidahouse/XCResultKit and https://github.com/gcharita/XMLMapper to generate a junit xml

**Comment by FabienLydoire** [comment]
Using https://github.com/fastlane-community/trainer here.

**Comment by MattiasBurstrom** [comment]
I would love to see Xcode 11 support for this project!
