### ISSUE TITLE
Unable to brew install since Xcode 11 support (v2.0.0)

### ISSUE THREAD

**Issue by asos-chrisblackmore** [TitouanVanBelle/XCTestHTMLReport#142]
`brew install https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/xchtmlreport.rb` is now failing since https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/141 was merged - it's expecting the `2.0.0` release to exist, but it hasn't been created yet (https://github.com/TitouanVanBelle/XCTestHTMLReport/releases).

Happy to assist to verify the fix!

**Comment by chrisballinger** [comment]
@asos-chrisblackmore 2.0.0 has been published

**Comment by sathyaNarayanQA** [comment]
I am still getting the below error message 

`Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 6e0e3c30331bb32bbf38ebd438c1ee3a168432c10ece0f0292c7fdbb72483e0c
  Actual: 4424d673d578e84e67fd96afa53a5bd3e80ec7acade65365a123af358c77b47e
 Archive: /Users/sathya.singh/Library/Caches/Homebrew/downloads/41e788a1388c05bb2f6c13680c4f49c93f6a3d5180d4ae568ffdb8558c003218--XCTestHTMLReport-2.0.0.tar.gz
To retry an incomplete download, remove the file above.`

**Comment by chrisballinger** [comment]
Now we're blocked on https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/144 getting approved from another maintainer. cc @TitouanVanBelle

**Comment by asos-chrisblackmore** [comment]
Yep, getting the same issue @sathyaNarayanQA.

Since https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/144 is now created, you could run `brew install https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/5d8644e0e5142172a5e4c756c1d17773d38c3f9e/xchtmlreport.rb` and it should work (pointing to the commit on that branch).

**Comment by chrisballinger** [comment]
Alrighty, everything is now merged. All systems go?

**Comment by sathyaNarayanQA** [comment]
Now the brew install is working fine with no issues. 

Thanks for the update !!

**Comment by asos-chrisblackmore** [comment]
👊

**Comment by ahmedeldeebfoodora** [comment]
Hello guys. I am trying to install 2.0.0 through bitrise using this curl, but it says cannot find. Am I missing something?

bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/develop/install.sh) '2.0.0'
