### ISSUE TITLE
Failed to find action_TestSummaries.plist

### ISSUE THREAD

**Issue by vimaljake** [TitouanVanBelle/XCTestHTMLReport#152]
XCTestHTMLReport 1.6.1
Error: Failed to find action_TestSummaries.plist in TestResults

Xcode 11 result bundle doesn't have action_TestSummaries.plist

**Comment by kenji21** [comment]
you should use version 2.x with Xcode 11

**Comment by vimaljake** [comment]
Working now thank you

**Comment by iOrangeTea** [comment]
@vimaljake Hello! I also have this problem.Please tell me how to resolve it.

**Comment by zeuge1983** [comment]
> you should use version 2.x with Xcode 11

But how to install 2.x version? On the page it says to run command 
bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/install.sh)
to install latest version which installs 1.6.1 

But how to install 2.1 version?
I found this page
https://swiftpackageregistry.com/TitouanVanBelle/XCTestHTMLReport
but how to install it with command
.Package(url: "https://github.com/TitouanVanBelle/XCTestHTMLReport.git", .upToNextMajor(from: "2.1.0"))    ?
