### ISSUE TITLE
The report index.html opens another file when trying to view it.

### ISSUE THREAD

**Issue by violetb116** [TitouanVanBelle/XCTestHTMLReport#173]
I am integrating the reports generated using this plugin with Jenkins using HTML publisher.
When I try to view the html, it downloads an attachment which is actually a file from the `.xcresult`. It contains only the test scheme name in it.
I see the same issue on local as well, on local, it opens that file containing the scheme name from`.xcresult`.
Is anyone else seeing this issue? how can I resolve it?

**Comment by pschneider** [comment]
What you are seeing is probably related to #147 which is a dup of #145

**Comment by nacho4d** [comment]
Fix Pull Request https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/201 has been merged. I will close this issue. If problem persists please reopen :)
