### ISSUE TITLE
When we open the report a download window is displayed

### ISSUE THREAD

**Issue by moatazeldebsy** [TitouanVanBelle/XCTestHTMLReport#178]
We are running our UI tests with `Bitrise` as a CI server and after that, we use the `XCTestHTML` report to create the index.html file then update the file to report.xcresult to `S3 bucket`, then displayed it as a static website. 

But the issue that the when we open the report it displayed download window as attached 

<img width="1271" alt="Screenshot 2020-07-02 at 21 20 44" src="https://user-images.githubusercontent.com/45570191/86401590-cabbf800-bcaa-11ea-8ae6-d123ee4f155a.png">

Configuration

```
- XCTestHTMLReport >> latest
- Xcode 11.5
```

**Comment by IliyanKafedzhiev** [comment]
I have the same issue when index.html is a remote file on Jenkins server.

**Comment by Mikuu** [comment]
same issue here, when open the index.html report, it automatically download a file

**Comment by liweiran10086** [comment]
This is what I do in Pipeline to avoid this problem
`sh script: "sed -i \"\" \'/iframe id=\"logs-iframe\"/d\' index.html"`

**Comment by moatazeldebsy** [comment]
@liweiran10086 this after generating the report, right?

**Comment by moatazeldebsy** [comment]
I got this error @liweiran10086 `sed: 1: "'iframe": invalid command code '`

**Comment by liweiran10086** [comment]
@moatazeldebsy 
The code I attached is used in Pipeline,
if you want to execute the code directly in terminal, use this 
`sed -i "" '/iframe id="logs-iframe"/d' index.html`

This command is to delete the lines contains `iframe id="logs-iframe"` 
![image](https://user-images.githubusercontent.com/44474610/93715645-1e98f780-fb9d-11ea-9f78-5599e44f218e.png)
