### ISSUE TITLE
Escape testcase name in junit report

### ISSUE THREAD

**Issue by yakimant** [TitouanVanBelle/XCTestHTMLReport#186]
After switch from xcpretty to XCTestHTMLReport, we have symbols not escaped in testcase names:

xcpretty:
```xml
<testcase classname='BumbleTests' name='testBumble_B&amp;R_FeedbackWith_Email' time='0.040'/>
<testcase classname='BumbleTests' name='testBumble_B&amp;R_FeedbackWithout_Email' time='0.034'/>`
```

```xml
<testcase classname='BumbleTests - iPhone 8 - 13.7' name='testBumble_B&R_FeedbackWith_Email' time='0.04'/>
<testcase classname='BumbleTests - iPhone 8 - 13.7' name='testBumble_B&R_FeedbackWithout_Email' time='0.03'/>
```

It causes issues for Teamcity junit xml parser for example: `The reference to entity "R_FeedbackWith_Email" must end with the ';' delimiter.`

**Comment by nacho4d** [comment]
@yakimant 
Hello, I have realized of this in the past. I thought it was trivial to reproduce and fix however I cannot define a function like yours. It leads to the following compile error to me. 
<img width="744" alt="Screen Shot 2020-10-10 at 22 56 10" src="https://user-images.githubusercontent.com/111651/95656815-ccb81180-0b4b-11eb-8b95-ff4ce67827ef.png">

Could you provide the specific function definition so I can create a test case and fix this?

**Comment by yakimant** [comment]
@nacho4d, we are generating the test name in runtime.

We will fix the name generation not to have '&', but maybe it's still a good idea to do escaping.

**Comment by yakimant** [comment]
On more case:

XCTestHTMLReport:
```xml
<testcase classname='BumbleTests - iPhone 8 - 13.7' name='testBumbleEncounters_'Invisible_Mode'_blocker' time='0.01'/>
<testcase classname='BumbleTests - iPhone 8 - 13.7' name='testBumbleEncounters_'Yes_votes_quota_reached'_blocker' time='0.02'/>
```

xcpretty:
```xml
<testcase classname='BumbleTests' name='testBumbleEncounters_&apos;Invisible_Mode&apos;_blocker' time='0.026'/>
<testcase classname='BumbleTests' name='testBumbleEncounters_&apos;Yes_votes_quota_reached&apos;_blocker' time='0.024'/>
```

**Comment by nacho4d** [comment]
Fixed in https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/196
