### ISSUE TITLE
Acceptance Tests

### ISSUE THREAD

**Issue by TitouanVanBelle** [TitouanVanBelle/XCTestHTMLReport#40]
Setup Cucumber + Capybara to run some acceptance tests

**Comment by SpeedyNassir** [comment]
@TitouanVanBelle  Is this created so as to integrate Cucumber with Xctest? If yes XCTest-Gherkin provides a solution.

https://cocoapods.org/pods/XCTest-Gherkin
https://github.com/net-a-porter-mobile/XCTest-Gherkin

Grouping test activities (a feature introduced in Xcode 9) in step def keeps the report simple and short in Gherkin format.

**Comment by TitouanVanBelle** [comment]
Hey @SpeedyNassir. No it's about covering the tool with test not to break anything when adding new features. 

But I was already aware of XCTest-Gherkin but I prefer Cucumberish because it really allows you to use .feature files.
