### ISSUE TITLE
Not generating reports if tests failed

### ISSUE THREAD

**Issue by mirza-ae** [TitouanVanBelle/XCTestHTMLReport#43]
I observed that if tests failed, then the report, "index.html" is not generated. The rest of the files like logs and attachments are.

Is this expected?

**Comment by mirza-ae** [comment]
My bad. Closing.

**Comment by TitouanVanBelle** [comment]
Hi @mirza-ae 
Would you mind explaining what the problem was? I'm interested

**Comment by mirza-ae** [comment]
Yes of course.

So I developed a shell script that executed the tests and generated a report. I set the script to exit as soon as failures are detected.

That's the reason why the reports were not being generated. Because I exit the script as soon as the tests failed.

**Comment by TitouanVanBelle** [comment]
Makes sense. Thanks for the explanation.

**Comment by mirza-ae** [comment]
A pleasure, and my compliments. It's a very nice utility you have here.

**Comment by TitouanVanBelle** [comment]
Thanks for the feedback. Spread the word! :)
