### ISSUE TITLE
Write activity containing failure in red

### ISSUE THREAD

**Issue by pjotal** [TitouanVanBelle/XCTestHTMLReport#44]
it was noticed that if the test is written using XCTContext.runActivity (introduced in XCode 9) and the failure happen on an action inside this actitivity, this activity is not highlighted which pretty much obliges the reader to expand all steps inside the test to find where the error occurred.

here is a sample test so you can reproduce:
```
func testFailToHighlight() {
        XCTContext.runActivity(named: "Step 1: it's a pass. Expect text in black") { _ in
            XCTAssertTrue(true)
        }
        XCTContext.runActivity(named: "Step 2: it's a fail. Expect text in RED") { _ in
            XCTAssertTrue(false)
        }
        XCTContext.runActivity(named: "Step 3: it's a pass. Expect text in black") { _ in
            XCTAssertTrue(true)
        }
}
```

**Comment by TitouanVanBelle** [comment]
Hi @pjotal 
Thanks for the idea. I just implemented it. You can download this temporary version to try it out and come back to me if that works for you or not

https://github.com/TitouanVanBelle/XCTestHTMLReport/raw/15ee61d6331978b80abb18b7cb28f45c69b49b5c/xchtmlreport

**Comment by pjotal** [comment]
sorry for the delay on checking that. the result is awesome! works like a charm.
can't wait to have that in an official release

**Comment by pjotal** [comment]
in order to reproduce it in your end, set the test to `continueAfterFailure = true` and create a workflow that fails in different places. this way you should see several steps failing after the one that originated the failure.

**Comment by TitouanVanBelle** [comment]
@pjotal Could you provide an example of test as well as screenshots showing the differences between Xcode and XCTestHTMLReport?
