### ISSUE TITLE
Add total amount of PASSED/FAILED tests

### ISSUE THREAD

**Issue by jeandeng** [TitouanVanBelle/XCTestHTMLReport#46]
Current version on master branch, there is only total test cases like "Selected tests - 7 tests (15s)" displayed in html report, but lack of summary for amount of PASSED or FAILED tests

**Comment by TitouanVanBelle** [comment]
Hi @jeandeng 
Could you maybe add screenshots of what you mean?

**Comment by jeandeng** [comment]
![image](https://user-images.githubusercontent.com/15320079/37645481-f0588a8c-2c61-11e8-8fa7-493a3a120cf3.png)
Take the screenshot of the code page as example, it can be seen from it that there is only amount of all test cases,
All tests-4 tests
XCTestHTMLReportSampleAppUITests.xctest - 4 tests
FirstSuite - 2 tests

all of the number reflects the total amount of tests, but not displays how many passed tests or how many failed tests

**Comment by TitouanVanBelle** [comment]
Ok. I see what you mean now. Thanks.

The data in that section is what XCTestHTMLReport gets directly from Xcode so it would be a bit dirty to update the data in there. Now what I could easily do is add between () the amount of tests, passed tests and failed tests in the toolbar above. That would look like this:

![screen shot 2018-03-20 at 11 50 58](https://user-images.githubusercontent.com/1162441/37650356-005e0c7c-2c35-11e8-99b1-07bc2bb2314f.png)

Would that work for you?

**Comment by jeandeng** [comment]
Yes, it looks well, and I can get the direct data without check the Xcode raw outputs. So if this function is available, please update it, thanks.

**Comment by TitouanVanBelle** [comment]
Sure. I'll add this in the next few days and will ping you.

**Comment by jeandeng** [comment]
Thanks TitouanVanBelle, it's great. Yeah, I noticed that the corner icon, it's a meaningful hint!
