### ISSUE TITLE
Test report missing information for 1 device?

### ISSUE THREAD

**Issue by ripunjayasaran** [TitouanVanBelle/XCTestHTMLReport#47]
Thanks a lot for creating this wonderful tool.

I am running 2 different tests (Test1 & Test2) in parallel on 2 different simulators. I am trying to run a test on 1 simulator and another test on another simulator and then generate the report using XCTestHTMLReport. The command that I am using is: 

`xcodebuild test -workspace my_workspace_name -scheme my_scheme_name -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' -only-testing:Test1 -resultBundlePath TestResults & xcodebuild test -workspace my_workspace_name -scheme my_scheme_name -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' -only-testing:Test2 -resultBundlePath TestResults`

Once this finishes executing, the report generated using `xchtmlreport -r TestResults` only contains results for the iPhone 8 simulator (Test2) and the results for the other iPhone 7 simulator are missing (Test1). I am assuming that this is because I am supplying the same `resultBundlePath` for both simulators and the latter is overwriting the results of the former.
In order to generate the reports for both simulators i have to specify a different `resultBundlePath` (i.e. `TestResults1` & `TestResults2`) for both simulators, but in this case 2 separate reports are generated and there is no combined report. Could you please let me know where I am going wrong here so that i could generate 1 report containing the results for both simulators ?
Also, what would be the command to generate the report if i have 2 different schemes and I want to run the tests in those 2 schemes on 2 different simulators.

Any help would be much appreciated.

**Comment by ripunjayasaran** [comment]
cc: @TitouanVanBelle

**Comment by TitouanVanBelle** [comment]
Hi @ripunjayasaran. Thanks for the feedback

I think your assumption is right and that one report is overridden by the other one when using the command you posted. One solution involving `xctesthtmlreport` receiving multiple `-r` values as input could be implemented, then the tool would spit out only one html report for all the bundle paths received as input. 

I'll take a look as soon as I have time and get back to you.

**Comment by ripunjayasaran** [comment]
Thanks a lot. Appreciate the prompt feedback. Looking forward to what you come up with :+1:

**Comment by TitouanVanBelle** [comment]
Could you maybe share with me a .zip containing TestResults1 and TestResults2 with me so that I can check on my end?

**Comment by TitouanVanBelle** [comment]
That's what you should see now when passing two reports and the -v options
```
$ xchtmlreport -r TestResults1 -r TestResults2 -v
XCTestHTMLReport 1.4.0

Parsing Test Summaries
  ▸ Searching for action_TestSummaries.plist in TestResults1

Parsing summary
  ▸ Found summary at TestResults1/1_Test/action_TestSummaries.plist
  ▸ Parsing RunDestination
  ▸ Parsing TargetDevice
  ▸ Parsing TestSummary
  ▸ Parsing Activity Logs
  ▸ Searching for action.xcactivitylog in TestResults1/1_Test
  ▸ Found TestResults1/1_Test/action.xcactivitylog
  ▸ Gunzipping activity logs
  ▸ Extracting useful activity logs

Parsing Test Summaries
  ▸ Searching for action_TestSummaries.plist in TestResults2

Parsing summary
  ▸ Found summary at TestResults2/1_Test/action_TestSummaries.plist
  ▸ Parsing RunDestination
  ▸ Parsing TargetDevice
  ▸ Parsing TestSummary
  ▸ Parsing Activity Logs
  ▸ Searching for action.xcactivitylog in TestResults2/1_Test
  ▸ Found TestResults2/1_Test/action.xcactivitylog
  ▸ Gunzipping activity logs
  ▸ Extracting useful activity logs

Building HTML..
  ▸ Writing report to TestResults1/index.html

Report successfully created at TestResults1/index.html
```

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : I figured out that the problem was with `bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/47_multiple_results/install.sh)` where it was installing the tool from master branch instead of from the branch were you pushed the changes because the install.sh script harcodes the branch as master. So after i installed the correct version of the tool i can run the tests in parallel and see the same output as you which is really wonderful. There is one thing that i am noticing and that is after i run the tests in parallel and they finish running, then if i clear the TestResults folders and run the tests in parallel again, then tests don't run on the second simulators and i get an exit code 65 for that simulator. I have to run any random test again on the 2nd simulator and then issue the command to run the tests in parallel on both simulators to get it up and running again. Any idea why would this happen?
Also, when you get a chance then please merge this to your master branch so that the rest of the world can benefit from this change. It's a pretty significant change and to my knowledge your reporting tool is the only tool that is accurately reporting results for parallel test runs. I am going to spread the word about this tool to the other folks so that you & your reporting tool get the praise that you deserve. I cannot thank you enough!!

**Comment by ripunjayasaran** [comment]
Also, you might wanna add some instructions on how to generate report for parallel test runs on your readme file after you merge the changes to your master branch.

**Comment by TitouanVanBelle** [comment]
Thanks a lot for the feedback @ripunjayasaran :)
I wanna run some more tests on this to make sure that it didn't break anything and that it's working properly but I'll merge as soon as that's done and release 1.5.0 as well.

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : any idea about the exit code 65 issue that i mentioned earlier?
