### ISSUE TITLE
Firefox browser issue

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [TitouanVanBelle/XCTestHTMLReport#52]
Hi @TitouanVanBelle, thanks for a great tool, but I am having issues viewing all the logs on firefox browser since on firefox it does not seem to scroll when you expand the tree view but the same file works on chrome. Also is possible to copy the Xcode log files to the same place where the HTML file has generated the reason being I can easily upload the logs to a remote server when the tests are run on CI.

**Comment by TitouanVanBelle** [comment]
Hi @Ashraf-Ali-aa. Thanks for the report. I just fixed the issue. I won't release it now but you can still install the version of the tool from the `develop` branch. Let me know if that works out for you.

Please open another ticket for the other issue you mentioning here.

**Comment by Ashraf-Ali-aa** [comment]
@TitouanVanBelle thanks, that has resolved the issue but I did notice that if the log error messages are very long it pushed the side image menu off the screen.

**Comment by TitouanVanBelle** [comment]
Can you provide a screenshot of the issue?

**Comment by Ashraf-Ali-aa** [comment]
@TitouanVanBelle here is the image (sorry I had to redact the image)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7900956/39144778-b4a81722-4729-11e8-8410-9c0e0729d2d2.png">
