### ISSUE TITLE
Show ignored tests and their count also in the report

### ISSUE THREAD

**Issue by ripunjayasaran** [TitouanVanBelle/XCTestHTMLReport#54]
The current report shows the passing and failing tests. It would be nice if it would also show the ignored tests and the count of ignored tests as well.

cc: @TitouanVanBelle 

P.S. - Thanks again for the wonderful report :)

**Comment by ripunjayasaran** [comment]
This is not a bug, but more like a feature request.

**Comment by TitouanVanBelle** [comment]
XCTestHTMLReport uses the result bundle as datasource for generating the report. I think that if you ignore a test then it will not appear in the `action_TestSummaries.plist` in the result bundle and therefore won't be even seen by the tool. 

Just to make sure, can you tell me how you ignore tests?

**Comment by ripunjayasaran** [comment]
I ignored the test by right clicking on the test in the XCode editor and choosing the 'Disable testname' option. It then makes an entry to the .xcscheme file.
