### ISSUE TITLE
Add Homebrew formula

### ISSUE THREAD

**Issue by chrisballinger** [TitouanVanBelle/XCTestHTMLReport#55]
It would be nice to be able to use Homebrew to download/update instead of using the install.sh script. Here's a simple guide: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

If you'd like I can create a formula for you!

**Comment by TitouanVanBelle** [comment]
Hi @chrisballinger 
Yes. That's be great to have it on Homebrew and you could provide the formula that'd be really helpful.
