### ISSUE TITLE
Add option for JUnit XML output

### ISSUE THREAD

**Issue by chrisballinger** [TitouanVanBelle/XCTestHTMLReport#62]
This tool handles multiple devices much better than the alternatives like xcpretty and [trainer](https://github.com/KrauseFx/trainer), so I'm wondering if I could easily add an option for JUnit XML output.

**Comment by TitouanVanBelle** [comment]
I'd be happy to add this to the tool. But then I think it would also make sense to rename the tool and the repo XCTestReport. What do you think?

**Comment by AhmedOsamaBarghash** [comment]
Where is the JUnit XML output located !!
