### ISSUE TITLE
1.6.0 Release Notes

### ISSUE THREAD

**Issue by chrisballinger** [TitouanVanBelle/XCTestHTMLReport#69]
Looks like we are getting pretty close to a 1.6.0 release.

Release notes:

* Add JUnit XML reports (`-j`) #63 
* Improved device list HTML #61 #53  
* Add Homebrew formula #57 
* Added Travis-CI support #68 

Changelog since 1.5.0: https://github.com/TitouanVanBelle/XCTestHTMLReport/compare/1.5.0...master

**Comment by TitouanVanBelle** [comment]
Yes we are. I'd like to include #56 too though since it's already fixed and just needs to be tested. I'll do that this weekend.

Also is there anything special to do for homebrew when releasing?

**Comment by chrisballinger** [comment]
Oh yeah it needs to point to the new tagged zip file and the sha256 hash updated. You'll have to make the tag first, then download the zip:

```
$ wget "https://github.com/TitouanVanBelle/XCTestHTMLReport/archive/1.6.0.tar.gz"
$ shasum -a 256 1.6.0.tar.gz
```

```ruby
# update these lines with the new values
  url "https://github.com/TitouanVanBelle/XCTestHTMLReport/archive/1.5.0.tar.gz"
  sha256 "ab8d917c867769693510de50f31d05bd6209875efe29fc1cbdfd344ce5c2ed88"
```

**Comment by TitouanVanBelle** [comment]
Released! Thanks for your contributions!
