### ISSUE TITLE
wrong path of screenshot attachment when test result is in subdirectory 

### ISSUE THREAD

**Issue by kamon70** [TitouanVanBelle/XCTestHTMLReport#79]
Step to reproduce
- Make test result directory ex; TestResults
- Put test result in subfolder ex; TestResults/device0
- Run command below
- run xchtmlreport -r ./TestResults/device0 -r ./TestResults/device1 -r ./TestResults/device2 -v

**Observed result**
- Report can be created in ./TestResults/device0 as expected (/)
- Wrong attachment links are found in the report ex;
/TestResults/**TestResults**/device0/1_Test/Attachments/Screenshot_34544FE6-9D9D-4A07-AADE-15EFE90102DD.jpg

**Expected result**
Link of attachment should be
**/TestResults/device0/**1_Test/Attachments/Screenshot_34544FE6-9D9D-4A07-AADE-15EFE90102DD.jpg

**Comment by TitouanVanBelle** [comment]
Hi @kamon70. Thanks for the report.

Which version did you experience this one?

**Comment by kamon70** [comment]
1.6.0

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : i see this issue happening for me as well even after #70 has been fixed. My test results are also in a sub-directory similar to to what @kamon70 mentioned earlier. I guess this is the reason why i only see screenshots in the report for the first device and not for the other devices.

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : I think due to this issue the screenshots are not even appearing in the report when running the tests on a single device or simulator. I think either this issue or the 1.6.0 release broke that feature. We might wanna fix this soon. cc: @chrisballinger

**Comment by TitouanVanBelle** [comment]
I just worked on a fix that uses absolute paths for screenshots instead of relative paths. Waiting for the review. Once it's merged we might wanna release a patch fixing this and the version number of 1.6.0.
