### ISSUE TITLE
wrong path for screenshot attachments for all but first device after downloading report from CI

### ISSUE THREAD

**Issue by algrubb** [TitouanVanBelle/XCTestHTMLReport#83]
**Affected Version**
`1.6.1`

**Repro steps**

* Generate test result bundles for multiple devices on a CI machine.
* Run xchtmlreport on the CI machine passing multiple result bundles

```
resultBundlePath="/Users/$(whoami)/Library/Caches/output/testResult"
xchtmlreport -r $resultBundlePath/test1 -r $resultBundlePath/test2 -r $resultBundlePath/test3 
```
* Download the full result bundle directory from the CI machine, that includes the `index.html` report created by xchtmlreport.
* Open the downloaded `index.html`.
* Observe the paths for screenshots for `test1` are correct but subsequent tests are incorrect. 

**Expected:**
Paths for screenshots are correct

**Actual:**
Paths for screenshots are only correct for the first test/device. 
(Ex. valid path from test1)
`file:///Users/<local_user>/Downloads/test-result-c116b6e5-a19f-4da9-a379-74dfaa49e69b/test1/1_Test/Attachments/Screenshot_2ED1B455-01F5-410F-9A35-F7B92F31D9FA.jpg`

(Ex. invalid path from test3)
`file:///Users/<ci_machine_name>/Library/Caches/output/485E6A64-A799-4B69-9D10-0E5456B8CB89/test3/1_Test/Attachments/Screenshot_FD4F06B9-4D92-4648-8E81-74B6A65D586C.jpg`

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : This is an issue on 1.6.1 as well.

**Comment by TitouanVanBelle** [comment]
@ripunjayasaran @algrubb 
Could you guys build `xchtmlreport` from source on the branch `83_fix_use_absolutepaths` and see if that works for you?

**Comment by KSelvam** [comment]
Hi @TitouanVanBelle 
I've installed the xchtmlreport using "83_fix_use_absolutepaths" branch. But still I'm unable to see the screen shots for devices except first one.

bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/83_fix_use_absolutepaths/install.sh)
