### ISSUE TITLE
Ability to generate report from bluepills for each simulator

### ISSUE THREAD

**Issue by ganjarpanji** [TitouanVanBelle/XCTestHTMLReport#93]
Is there such a way to generate report from bluepills ? that basically using junit or json type report.
https://github.com/linkedin/bluepill
Thanks!

**Comment by TitouanVanBelle** [comment]
Hi @ganjarpanji 

No there is no plan to support bluebell, especially now that Xcode 10 provides a way to execute tests in parallel in the Simulator.

Cheers
