### ISSUE TITLE
A testresult bundle created when no tests were run will hang xchtmlreport

### ISSUE THREAD

**Issue by maxelrod** [TitouanVanBelle/XCTestHTMLReport#94]
1. Do a xcodebuild test with zero tests (because you misspelled your test suite or something)
2. pass the resulting test result bundle to to xchtmlreport via -r

Expected:
No hang  and / or message about no test results found

Actual:
Hang

**Comment by maxelrod** [comment]
Normally, would not do this, but xchtmlreport hanging in a pipeline is bad.

**Comment by TitouanVanBelle** [comment]
Hi @maxelrod 
Thanks for the report. You're right hanging in a pipeline is pretty bad. I think I fixed it in `94_xctesthtmlreport_hanging` could you give it a try and let me know if that fixes it. I also tried it by providing the command line a bundle that doesn't contain any tests and it seems to work.

Cheers
