### ISSUE TITLE
Script is hanging when running the html report command on my Logs folder

### ISSUE THREAD

**Issue by rupeshbonda1985** [TitouanVanBelle/XCTestHTMLReport#99]
Generated Logs and placed in a folder. Now when I run the script it is hanging and not providing any result and the command used is as follows 
/usr/local/bin/xchtmlreport -r /Users/jenkinsslave/workspace/Automation_iOS/Automation_test_build@2/MobiConnect/Logs
and then it displays XCTestHTMLReport 1.6.1 and nothing happens. 

Please let me know for more information 

[Logs.zip](https://github.com/TitouanVanBelle/XCTestHTMLReport/files/2354970/Logs.zip)

**Comment by TitouanVanBelle** [comment]
Hi @rupeshbonda1985 
Thanks for the report. This issue seems to be similar to #94. Could you try to fix there and tell me if it fixes your problem.

**Comment by gangadharbonda** [comment]
@TitouanVanBelle 
1) I downloaded the branch XCTestHTMLReport-94_xctesthtmlreport_hanging and ran the install.sh. 
2) Now downloaded the file Logs.zip in the above comment and ran the command "xchtmlreport -r Logs"
Application 
3) Observed terminal is hang

Please let me know if I need to follow differently

**Comment by TitouanVanBelle** [comment]
Works fine on my machine. I'm guessing you're still using the old version of xchtmlreport

Old version
```
$ xchtmlreport -r Logs -v
XCTestHTMLReport 1.6.1

Parsing Test Summaries
  ▸ Searching for action_TestSummaries.plist in Logs

Parsing summary
  ▸ Found summary at Logs/Test/action_TestSummaries.plist
  ▸ Parsing RunDestination
  ▸ Parsing TargetDevice
  ▸ Parsing TestSummary
^C
```

New version
```
$ ./xchtmlreport -r Logs -v
XCTestHTMLReport 1.6.1

Parsing Test Summaries
  ▸ Searching for action_TestSummaries.plist in Logs

Parsing summary
  ▸ Found summary at Logs/Test/action_TestSummaries.plist
  ▸ Parsing RunDestination
  ▸ Parsing TargetDevice
  ▸ Parsing TestSummary
  ▸ Parsing Activity Logs
  ▸ Searching for action.xcactivitylog in Logs/Test
  ▸ Found Logs/Test/action.xcactivitylog
  ▸ Gunzipping activity logs
  ▸ Extracting useful activity logs

Building HTML..
  ▸ Writing report to Logs/index.html

Report successfully created at Logs/index.html
```

**Comment by gangadharbonda** [comment]
@TitouanVanBelle 
I tried to get the version on following branch "94_xctesthtmlreport_hanging" and install using brew and I still see the same issue. Below are the steps I followed. Let me know if I have to follow differently

brew reinstall https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/94_xctesthtmlreport_hanging/xchtmlreport.rb
######################################################################## 100.0%
==> Reinstalling xchtmlreport 
==> Downloading https://github.com/TitouanVanBelle/XCTestHTMLReport/archive/1.6.1.tar.gz
Already downloaded: /Users/gbonda/Library/Caches/Homebrew/downloads/4a7fdbb7e270ce88999d977391e887856c4b915235be35b479d2a4f8e3095314--XCTestHTMLReport-1.6.1.tar.gz
==> xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace XCTestHTMLReport.xcworkspace -scheme XCTestHTMLReport -configuration Release
🍺  /usr/local/Cellar/xchtmlreport/1.6.1: 5 files, 10MB, built in 13 seconds
2016-sierra-macbook-pro:XCTestHTMLReport-94_xctesthtmlreport_hanging gbonda$ xchtmlreport -r /Users/gbonda/Desktop/Gangadhar/XCTestHTMLReport-94_xctesthtmlreport_hanging/Logs -v
XCTestHTMLReport 1.6.1

Parsing Test Summaries
  ▸ Searching for action_TestSummaries.plist in /Users/gbonda/Desktop/Gangadhar/XCTestHTMLReport-94_xctesthtmlreport_hanging/Logs

Parsing summary
  ▸ Found summary at /Users/gbonda/Desktop/Gangadhar/XCTestHTMLReport-94_xctesthtmlreport_hanging/Logs/Test/action_TestSummaries.plist
  ▸ Parsing RunDestination
  ▸ Parsing TargetDevice
  ▸ Parsing TestSummary

**Comment by gangadharbonda** [comment]
@TitouanVanBelle 
I still see the issue after installing the latest version and below is the console output
xchtmlreport -r Logs -v
XCTestHTMLReport 1.6.1

Parsing Test Summaries
  ▸ Searching for action_TestSummaries.plist in Logs

Parsing summary
  ▸ Found summary at Logs/Test/action_TestSummaries.plist
  ▸ Parsing RunDestination
  ▸ Parsing TargetDevice
  ▸ Parsing TestSummary
